[[includes]]
url = "https://github.com/philipdexter/std.mold"

[recipes.build]
help = "Build using cargo"
command = ["cargo", "build"]

[recipes.check]
help = "Check for errors using cargo"
command = ["cargo", "check"]

[recipes.test]
help = "Run tests using cargo"
command = ["cargo", "test"]

[recipes.install]
help = "Install the current project using cargo"
command = ["cargo", "install", "--force", "--path", "."]

[recipes.fmt]
help = "Format using rustfmt"
command = ["cargo", "fmt"]

[recipes.clean]
help = "Clean build artifacts using cargo"
command = ["cargo", "clean"]

[recipes.clean-self]
help = "Clean build artifacts using cargo"
type = "sh"

[recipes.lint]
help = "Lint using clippy"
command = ["cargo", "clippy", "--", "-D", "warnings"]
deps = ["clean-self"]
